[project]
name = "yijian-next"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "camel-ai[all]>=0.2.57",
    "markitdown[pdf]>=0.0.2",
]
